#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
VENV_PYTHON="$DIR/.venv/bin/python3"

if [ ! -f "$VENV_PYTHON" ]; then
    echo "Ambiente virtual não encontrado em $VENV_PYTHON"
    exit 1
fi

exec "$VENV_PYTHON" "$DIR/main.py" "$@"
